# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 537)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox_input = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_input.setGeometry(QtCore.QRect(30, 20, 481, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_input.setFont(font)
        self.groupBox_input.setObjectName("groupBox_input")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_input)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_startDate = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_startDate.setFont(font)
        self.label_startDate.setObjectName("label_startDate")
        self.gridLayout.addWidget(self.label_startDate, 0, 0, 1, 1)
        self.dateEdit_startDate = QtWidgets.QDateEdit(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_startDate.setFont(font)
        self.dateEdit_startDate.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.dateEdit_startDate.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit_startDate.setCalendarPopup(True)
        self.dateEdit_startDate.setObjectName("dateEdit_startDate")
        self.gridLayout.addWidget(self.dateEdit_startDate, 0, 1, 1, 1)
        self.label_startValue = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_startValue.setFont(font)
        self.label_startValue.setObjectName("label_startValue")
        self.gridLayout.addWidget(self.label_startValue, 1, 0, 1, 1)
        self.doubleSpinBox_startValue = QtWidgets.QDoubleSpinBox(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_startValue.setFont(font)
        self.doubleSpinBox_startValue.setMinimum(0.0)
        self.doubleSpinBox_startValue.setMaximum(10000.0)
        self.doubleSpinBox_startValue.setSingleStep(0.01)
        self.doubleSpinBox_startValue.setObjectName("doubleSpinBox_startValue")
        self.gridLayout.addWidget(self.doubleSpinBox_startValue, 1, 1, 1, 1)
        self.label_mesUnit = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_mesUnit.setFont(font)
        self.label_mesUnit.setObjectName("label_mesUnit")
        self.gridLayout.addWidget(self.label_mesUnit, 2, 0, 1, 1)
        self.comboBox_mesUnit = QtWidgets.QComboBox(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_mesUnit.setFont(font)
        self.comboBox_mesUnit.setObjectName("comboBox_mesUnit")
        self.comboBox_mesUnit.addItem("")
        self.comboBox_mesUnit.addItem("")
        self.comboBox_mesUnit.addItem("")
        self.gridLayout.addWidget(self.comboBox_mesUnit, 2, 1, 1, 1)
        self.label_mesDate = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_mesDate.setFont(font)
        self.label_mesDate.setObjectName("label_mesDate")
        self.gridLayout.addWidget(self.label_mesDate, 3, 0, 1, 1)
        self.dateEdit_mesDate = QtWidgets.QDateEdit(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_mesDate.setFont(font)
        self.dateEdit_mesDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 8), QtCore.QTime(0, 0, 0)))
        self.dateEdit_mesDate.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.dateEdit_mesDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_mesDate.setCalendarPopup(True)
        self.dateEdit_mesDate.setObjectName("dateEdit_mesDate")
        self.gridLayout.addWidget(self.dateEdit_mesDate, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.groupBox_result = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_result.setGeometry(QtCore.QRect(30, 300, 481, 191))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_result.setFont(font)
        self.groupBox_result.setObjectName("groupBox_result")
        self.label_resUnit = QtWidgets.QLabel(self.groupBox_result)
        self.label_resUnit.setGeometry(QtCore.QRect(22, 80, 116, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_resUnit.setFont(font)
        self.label_resUnit.setObjectName("label_resUnit")
        self.label_unit = QtWidgets.QLabel(self.groupBox_result)
        self.label_unit.setGeometry(QtCore.QRect(250, 80, 37, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_unit.setFont(font)
        self.label_unit.setObjectName("label_unit")
        self.label_resMBq = QtWidgets.QLabel(self.groupBox_result)
        self.label_resMBq.setGeometry(QtCore.QRect(22, 108, 120, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_resMBq.setFont(font)
        self.label_resMBq.setObjectName("label_resMBq")
        self.label_MBq = QtWidgets.QLabel(self.groupBox_result)
        self.label_MBq.setGeometry(QtCore.QRect(250, 108, 40, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_MBq.setFont(font)
        self.label_MBq.setObjectName("label_MBq")
        self.label_resmCi = QtWidgets.QLabel(self.groupBox_result)
        self.label_resmCi.setGeometry(QtCore.QRect(22, 136, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_resmCi.setFont(font)
        self.label_resmCi.setObjectName("label_resmCi")
        self.label_mCi = QtWidgets.QLabel(self.groupBox_result)
        self.label_mCi.setGeometry(QtCore.QRect(250, 136, 33, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_mCi.setFont(font)
        self.label_mCi.setObjectName("label_mCi")
        self.label_resDate = QtWidgets.QLabel(self.groupBox_result)
        self.label_resDate.setGeometry(QtCore.QRect(22, 52, 169, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_resDate.setFont(font)
        self.label_resDate.setObjectName("label_resDate")
        self.label_date = QtWidgets.QLabel(self.groupBox_result)
        self.label_date.setGeometry(QtCore.QRect(250, 52, 101, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Activity Conversion"))
        self.groupBox_input.setTitle(_translate("MainWindow", "Input"))
        self.label_startDate.setText(_translate("MainWindow", "reference date:"))
        self.dateEdit_startDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_startValue.setText(_translate("MainWindow", "start value:"))
        self.label_mesUnit.setText(_translate("MainWindow", "measuring unit:"))
        self.comboBox_mesUnit.setItemText(0, _translate("MainWindow", "Unit"))
        self.comboBox_mesUnit.setItemText(1, _translate("MainWindow", "mCi"))
        self.comboBox_mesUnit.setItemText(2, _translate("MainWindow", "MBq"))
        self.label_mesDate.setText(_translate("MainWindow", "requested date:"))
        self.dateEdit_mesDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.groupBox_result.setTitle(_translate("MainWindow", "Result"))
        self.label_resUnit.setText(_translate("MainWindow", "Result in Unit"))
        self.label_unit.setText(_translate("MainWindow", "Unit"))
        self.label_resMBq.setText(_translate("MainWindow", "Result in MBq"))
        self.label_MBq.setText(_translate("MainWindow", "MBq"))
        self.label_resmCi.setText(_translate("MainWindow", "Result in mCi"))
        self.label_mCi.setText(_translate("MainWindow", "mCi"))
        self.label_resDate.setText(_translate("MainWindow", "Values for the date:"))
        self.label_date.setText(_translate("MainWindow", "Result-Date"))
