# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 587)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox_input = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_input.setGeometry(QtCore.QRect(30, 20, 481, 241))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_input.setFont(font)
        self.groupBox_input.setObjectName("groupBox_input")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_input)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_startDate = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_startDate.setFont(font)
        self.label_startDate.setObjectName("label_startDate")
        self.gridLayout.addWidget(self.label_startDate, 0, 0, 1, 1)
        self.dateEdit_startDate = QtWidgets.QDateEdit(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_startDate.setFont(font)
        self.dateEdit_startDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 8), QtCore.QTime(0, 0, 0)))
        self.dateEdit_startDate.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.dateEdit_startDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_startDate.setCalendarPopup(True)
        self.dateEdit_startDate.setObjectName("dateEdit_startDate")
        self.gridLayout.addWidget(self.dateEdit_startDate, 0, 1, 1, 1)
        self.label_startValue = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_startValue.setFont(font)
        self.label_startValue.setObjectName("label_startValue")
        self.gridLayout.addWidget(self.label_startValue, 1, 0, 1, 1)
        self.doubleSpinBox_startValue = QtWidgets.QDoubleSpinBox(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.doubleSpinBox_startValue.setFont(font)
        self.doubleSpinBox_startValue.setObjectName("doubleSpinBox_startValue")
        self.gridLayout.addWidget(self.doubleSpinBox_startValue, 1, 1, 1, 1)
        self.label_mesUnit = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_mesUnit.setFont(font)
        self.label_mesUnit.setObjectName("label_mesUnit")
        self.gridLayout.addWidget(self.label_mesUnit, 2, 0, 1, 1)
        self.comboBoxMmesUnit = QtWidgets.QComboBox(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxMmesUnit.setFont(font)
        self.comboBoxMmesUnit.setObjectName("comboBoxMmesUnit")
        self.comboBoxMmesUnit.addItem("")
        self.comboBoxMmesUnit.addItem("")
        self.comboBoxMmesUnit.addItem("")
        self.gridLayout.addWidget(self.comboBoxMmesUnit, 2, 1, 1, 1)
        self.label_mesDate = QtWidgets.QLabel(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_mesDate.setFont(font)
        self.label_mesDate.setObjectName("label_mesDate")
        self.gridLayout.addWidget(self.label_mesDate, 3, 0, 1, 1)
        self.dateEdit_mesDate = QtWidgets.QDateEdit(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit_mesDate.setFont(font)
        self.dateEdit_mesDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 8), QtCore.QTime(0, 0, 0)))
        self.dateEdit_mesDate.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.dateEdit_mesDate.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit_mesDate.setCalendarPopup(True)
        self.dateEdit_mesDate.setObjectName("dateEdit_mesDate")
        self.gridLayout.addWidget(self.dateEdit_mesDate, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.groupBox_result = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_result.setGeometry(QtCore.QRect(40, 300, 481, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_result.setFont(font)
        self.groupBox_result.setObjectName("groupBox_result")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Activity Conversion"))
        self.groupBox_input.setTitle(_translate("MainWindow", "Input"))
        self.label_startDate.setText(_translate("MainWindow", "reference date:"))
        self.dateEdit_startDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label_startValue.setText(_translate("MainWindow", "start value:"))
        self.label_mesUnit.setText(_translate("MainWindow", "measuring unit:"))
        self.comboBoxMmesUnit.setItemText(0, _translate("MainWindow", "Unit"))
        self.comboBoxMmesUnit.setItemText(1, _translate("MainWindow", "mCi"))
        self.comboBoxMmesUnit.setItemText(2, _translate("MainWindow", "MBq"))
        self.label_mesDate.setText(_translate("MainWindow", "requested date:"))
        self.dateEdit_mesDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.groupBox_result.setTitle(_translate("MainWindow", "Result"))
